### ISSUE TITLE
404 Website hard to read

### ISSUE THREAD

**Issue by GsnailG** [JHay0112/JHay0112.github.io#19]
![error](https://user-images.githubusercontent.com/61771862/119759774-ee101700-befc-11eb-8805-44cda1a9d941.PNG)
as seen above, the text is hard to read because the super cool logo is in the background, I was using Firefox and Windows 10

**Comment by JHay0112** [comment]
I have reproduced the error, I am investigating it now.

**Comment by JHay0112** [comment]
@GsnailG Commit [852c9d2](https://github.com/JHay0112/JHay0112.github.io/commit/852c9d2bbc0e94241fab0d4484951bfa36d57e6a) should fix this, can I get you to check this? The fix may not be immediately available or require a hard refresh.

**Comment by GsnailG** [comment]
Hi, I was not able to use the exact same device as I did in https://github.com/JHay0112/JHay0112.github.io/issues/19#issue-903156610 , as I was using another computer, but I have used roughly the same computer, the same browser, and the same OS, and I was not able to replicate the original bug, therefore I believe that the bug is fixed! 
![jordan](https://user-images.githubusercontent.com/61771862/119929741-2c2b3a80-bfd2-11eb-8bf1-d81acbc07839.PNG)

**Comment by JHay0112** [comment]
Awesome, thank you!
